version: '3.8'

services:

  geoinformation-service:
    build: 
      context: ./ 
      dockerfile: DockerFile_GeoInformationService
    ports:
      - "50001:80"
    environment:
      - DOTNET_ENVIRONMENT=Docker
