#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY ["src/MetaQuotes.Services.GeoInformationService.Api/MetaQuotes.Services.GeoInformationService.Api.csproj", "src/MetaQuotes.Services.GeoInformationService.Api/"]
COPY ["src/MetaQuotes.Services.GeoInformationService.Application/MetaQuotes.Services.GeoInformationService.Application.csproj", "src/MetaQuotes.Services.GeoInformationService.Application/"]
COPY ["src/MetaQuotes.Services.GeoInformationService.Domain/MetaQuotes.Services.GeoInformationService.Domain.csproj", "src/MetaQuotes.Services.GeoInformationService.Domain/"]
COPY ["src/MetaQuotes.Services.GeoInformationService.Infrastructure/MetaQuotes.Services.GeoInformationService.Infrastructure.csproj", "src/MetaQuotes.Services.GeoInformationService.Infrastructure/"]
RUN dotnet restore "src/MetaQuotes.Services.GeoInformationService.Api/MetaQuotes.Services.GeoInformationService.Api.csproj"
COPY . .
WORKDIR "/src/src/MetaQuotes.Services.GeoInformationService.Api"
RUN dotnet build "MetaQuotes.Services.GeoInformationService.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "MetaQuotes.Services.GeoInformationService.Api.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MetaQuotes.Services.GeoInformationService.Api.dll"]